project:
  title: ICS slides
  lib-dir: ../../slides/quarto_files
format:
  revealjs: 
    slide-number: false
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: ../../slides/images/quarto.png
    css: ../../slides/ics.css
    navigation-mode: vertical
    footer: <https://aaronbloomfield.github.io/ics>
    controls: false
    template-partials:
      - ../../slides/title-slide.html
      - ../../slides/toc-slide.html
    toc: false
    toc-depth: 1
    toc-title: Contents
    theme: dark
    menu: false
    center: false
    link-external-newwindow: true
    link-external-icon: true
